#!/usr/bin/env python

import subprocess
import rospy

if __name__ == '__main__':
    try:
        subprocess.call(["roslaunch", "turtlebot3_gazebo", "turtlebot3_empty_world.launch"])
    except rospy.ROSInterruptException:
        rospy.loginfo("Action terminated")